"""update to gmail

Revision ID: 045067de780c
Revises: d39a647bd609
Create Date: 2026-02-09 06:43:13.007010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045067de780c'
down_revision = 'd39a647bd609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('employees_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['gmail'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('employees_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('gmail')

    # ### end Alembic commands ###
