"""remove projectid in logwork table

Revision ID: 4d5cc253c0c1
Revises: 974c59fbcdaf
Create Date: 2026-02-11 04:17:30.993698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5cc253c0c1'
down_revision = '974c59fbcdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('logworks_project_id_fkey'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('logworks_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
