"""add week and month for ticket

Revision ID: 5f504cf7cae4
Revises: 45506c0634b6
Create Date: 2026-02-26 01:04:44.674488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f504cf7cae4'
down_revision = '45506c0634b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tickets_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_week'), ['week'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_week'))
        batch_op.drop_index(batch_op.f('ix_tickets_month'))
        batch_op.drop_column('month')
        batch_op.drop_column('week')

    # ### end Alembic commands ###
