"""init all tables

Revision ID: 974c59fbcdaf
Revises: 
Create Date: 2026-02-11 04:04:04.362514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974c59fbcdaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vn_full_name', sa.String(length=255), nullable=False),
    sa.Column('en_full_name', sa.String(length=255), nullable=False),
    sa.Column('employeeId', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('authorize_role', sa.Enum('MEMBER', 'ADMIN', name='employee_role'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employeeId'), ['employeeId'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_role_id'), ['role_id'], unique=True)

    op.create_table('system_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('param_key', sa.String(length=100), nullable=False),
    sa.Column('param_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_parameters_param_key'), ['param_key'], unique=True)

    op.create_table('ticket_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_statuses_status_id'), ['status_id'], unique=True)

    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_types_type_id'), ['type_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pm_name', sa.String(length=255), nullable=False),
    sa.Column('project_link', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_project_id'), ['project_id'], unique=True)

    op.create_table('logworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('loghours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logworks_log_date'), ['log_date'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('allocation_percent', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('ticket_link', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('ticket_type_id', sa.UUID(), nullable=True),
    sa.Column('ticket_status_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_status_id'], ['ticket_statuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_ticket_id'), ['ticket_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_status_id'), ['ticket_status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_type_id'), ['ticket_type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_type_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_status_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_id'))

    op.drop_table('tickets')
    op.drop_table('project_members')
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logworks_log_date'))

    op.drop_table('logworks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_id'))

    op.drop_table('projects')
    with op.batch_alter_table('ticket_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_types_type_id'))

    op.drop_table('ticket_types')
    with op.batch_alter_table('ticket_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_statuses_status_id'))

    op.drop_table('ticket_statuses')
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_parameters_param_key'))

    op.drop_table('system_parameters')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_id'))

    op.drop_table('roles')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employeeId'))

    op.drop_table('employees')
    op.drop_table('banks')
    # ### end Alembic commands ###
