"""add year column to logwork table

Revision ID: add_year_to_logwork
Revises: remove_logdate_add_month
Create Date: 2026-02-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_year_to_logwork'
down_revision = 'remove_logdate_add_month'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(4), nullable=True))
        batch_op.create_index(batch_op.f('ix_logworks_year'), ['year'])
    
    # Update existing records to have year 2026
    op.execute("UPDATE logworks SET year = '2026' WHERE year IS NULL")
    
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.alter_column('year', existing_type=sa.String(4), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logworks_year'))
        batch_op.drop_column('year')

    # ### end Alembic commands ###
