"""revert to email

Revision ID: d0bb308ca661
Revises: 045067de780c
Create Date: 2026-02-09 06:44:46.015429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bb308ca661'
down_revision = '045067de780c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('employees_gmail_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('gmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('employees_gmail_key'), ['gmail'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
