"""remove log_date and add month to logwork table

Revision ID: remove_logdate_add_month
Revises: add_project_dates
Create Date: 2026-02-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_logdate_add_month'
down_revision = 'add_project_dates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(2), nullable=True))
        batch_op.drop_column('log_date')

    # Update null values to a default before setting NOT NULL
    op.execute("UPDATE logworks SET month = '1' WHERE month IS NULL")
    
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.alter_column('month', existing_type=sa.String(2), nullable=False)
        batch_op.create_index(batch_op.f('ix_logworks_month'), ['month'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logworks_month'))
        batch_op.add_column(sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('month')
        batch_op.create_index('ix_logworks_log_date', ['log_date'])

    # ### end Alembic commands ###
